---
title: "PAC Graph"
author: "Cameron Eller"
date: "2024-01-11"
output: html_document
---

```{r}
library(data.table)
library(igraph)
library(tidyverse)

# load in all of the donations data
donations = read_csv("../../large_contributions_and_scores.csv") 
# note: github wont allow for uploading as large a file as "large_contributions_and_scores.csv" so it is stored outside of the repo on our personal computers

print(nrow(donations))

pac_donations = donations %>%
  filter(pac_or_individual == 'p')

print(nrow(pac_donations))

```

Group-by Mutate:
```{r}
# creating a condensed pac donations data frame
clean_pac_df <- pac_donations |>
  group_by(donor_name, candidate_name) |>
  mutate(amount = sum(amount)) |> 
  select(donor_name, candidate_name, candidate_party, score, lifetime_score, name, amount) |> 
  ungroup()

# making the data frame smaller by taking unique observations
clean_pac_df <- unique(clean_pac_df)

# note: many of the pacs donated multiple times to the same candidate, since our analysis does not depend on amount of donations or time donated, we collapsed all donations from the same donor to the same candidate and used their total donated amount

```

```{r}
pac_donations %>% 
  group_by(donor_name) %>% 
  summarize(total = sum(amount)) %>% 
  arrange(-total)

```


```{r}
# creating the edge list of the pac donors
edge_list <- clean_pac_df |>
  select(donor_name, candidate_name, amount)

# using the edge list to create the first graph (not directed)
g <- graph_from_data_frame(d=edge_list, directed=FALSE)

# change the graph type to bipartite
V(g)$type <- bipartite_mapping(g)$type

# summing the total amount donated to the candidate
donor_candidate_amount <- edge_list %>%
  group_by(donor_name, candidate_name) %>%
  summarize(total_amount = sum(amount))

# pairing the candidates with their donated total
candidate_pairs <- donor_candidate_amount %>%
  full_join(donor_candidate_amount, by="donor_name") %>%
  filter(candidate_name.x != candidate_name.y) %>%
  group_by(candidate_name.x, candidate_name.y) %>%
  summarize(weight = sum(total_amount.x + total_amount.y))

# creating the one mode projection
candidate_projection <- bipartite_projection(g, which=TRUE)
V(candidate_projection)$name <- V(g)[V(g)$type == TRUE]$name

# vectorized code getting the edge ids
get_edge_ids_vectorized <- function(graph, from, to){
  mapply(function(f, t)get.edge.ids(graph, c(f, t)), from, to)
}

# using edge ids to pair candidates and weights
edge_ids <- get_edge_ids_vectorized(candidate_projection, 
                                    candidate_pairs$candidate_name.x,
                                    candidate_pairs$candidate_name.y)

E(candidate_projection)$weight[edge_ids] <- candidate_pairs$weight



```

```{r}
# running walktrap
wt_communities <- cluster_walktrap(candidate_projection, steps = 1)

membership <- membership(wt_communities)

V(candidate_projection)$community <- membership

str <- strength(candidate_projection, mode="all")

# creating a string for the members of each community
for (i in unique(membership)) {
  cat("Community", i, ":", names(V(candidate_projection))[membership == i], "\n")
}
```

```{r}
# graphing the network
names_of_interest = names(sort(str, decreasing = TRUE)[1:5])
l = layout_with_lgl(candidate_projection, 
                    area = vcount(candidate_projection)^5, 
                    cellsize = sqrt(vcount(candidate_projection)^5))

print(names_of_interest)
last_two_words <- function(name) {
  words <- strsplit(name, " ")[[1]]
  if (length(words) >= 2) {
    paste(tail(words, 2), collapse=" ")
  } else {
    name  
  }
}

vertex_indices = match(names_of_interest, V(candidate_projection)$name)
short_labels <- sapply(V(candidate_projection)$name[vertex_indices], last_two_words)
vlabs = rep(NA, vcount(candidate_projection))
vlabs[vertex_indices] <- short_labels

g = max(str)
print(g)
str = str/g

par(mar=c(0,0,0,0))
plot(candidate_projection, 
     vertex.color=V(candidate_projection)$community,
     vertex.label=vlabs, #V(candidate_projection)$name, 
     vertex.size=str*10, 
     vertex.label.cex = 0.5,
     edge.arrow.size=0, 
     edge.curved=0.1, 
     edge.width=0.0023,
     layout=l
)

```

Writing the graph to a file:
```{r}
write_graph(candidate_projection, "pac_graph.graphml", format = "graphml")

```

Reading in a graph from a file:
```{r}
loaded_graph <- read.graph("pac_graph.graphml", format = "graphml")

```

Creating a communities data frame:
```{r}
# creating an empty dataframe with two columns, community and congresspeople
communities_df <- data.frame(matrix(ncol = 2, nrow = length(unique(membership))))
colnames(communities_df) <- c("community", "congresspeople")

# add all of the communities to the dataframe (currently out of order)
for (i in unique(membership)) {
  communities_df$community[[i]] <- unique(membership)[i]
}

# reorder the communities from first to last
communities_df <- communities_df |>
  arrange(community)

# add the people in each community as a single string
for (i in unique(membership)) {
  communities_df$congresspeople[[i]] <- paste(names(V(candidate_projection)[membership == i]), sep="", collapse=", ") 
}

# write the community data frame to a csv
write.csv(communities_df, "pac_communities_by_community.csv")

```
